### ISSUE TITLE
createVideo() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by ScripticusKodius** [fabrree/videoGenerator#1]
createVideo(mp3, quoteText,bgMusic, bgVideo,i) # createVideo(quoteMp3,bgMusic,bgVideo)
TypeError: createVideo() takes 4 positional arguments but 5 were given

**Comment by DuxSec** [comment]
Thanks, was on accident will let u know when I fixed it!

**Comment by DuxSec** [comment]
Solved :)
