### ISSUE TITLE
can't create more than 10 videos

### ISSUE THREAD

**Issue by ScripticusKodius** [fabrree/videoGenerator#10]
it just create 10 videos ( vid_0 to vid_9 ) and stops with the following errors

"main.py", line 361, in <module>
    videoloop = mainVideoLoop(data) 

"main.py", line 247, in mainVideoLoop
    createVideo(quoteText, bgMusic, bgVideo, i, ttsAudio)

"main.py", line 132, in createVideo
    print(f"Introtext we will use: {introText[videoNumber]}")
IndexError: list index out of range

**Comment by DuxSec** [comment]
Hi, aware of the issue, will be fixed in next update.

**Comment by DuxSec** [comment]
fixed in new version
