### ISSUE TITLE
Match statements require Python 3.10 or newer

### ISSUE THREAD

**Issue by KalvinThien** [fabrree/videoGenerator#12]
I have 1 problem.
I use python 3.7.9, can you help me

 match choice:
               ^
SyntaxError: invalid syntax

**Comment by KalvinThien** [comment]
sr, im fixed, thanks bro, this is code after fixed

   changes = ""
while True:
    with open('config.json', 'r') as file:
        data = json.load(file)
    os.system('cls' if os.name=='nt' else 'clear')
    loopPrint = (f"""{bcolors.HEADER}

        /__/|__                                                            __//|
        |__|/_/|__                 Video generator v1.1.0                _/_|_||
        |_|___|/_/|__                     fabbree                     __/_|___||
        |___|____|/_/|__                                           __/_|____|_||
        |_|___|_____|/_/|_________________________________________/_|_____|___||
        |___|___|__|___|/__/___/___/___/___/___/___/___/___/___/_|_____|____|_||
        |_|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___||
        |___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|_||
        |_|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|___|/{bcolors.ENDC}

                    {bcolors.OKGREEN}   {changes}{bcolors.ENDC}

    Current configurations:
        Your Pexels API key: {bcolors.WARNING}{data['pexelsAPIKey']}{bcolors.ENDC}
        Amount of videos to create: {bcolors.WARNING}{data['amountOfVideosToMake']}{bcolors.ENDC}

    Options menu:
        1) Change amount of videos to create
        2) Change Pexels API key
        3) Start generating videos
        4) Check if ImageMagicks is installed (necessary to run)
        5) Exit

    Enter your choice: """)
    choice = int(input(loopPrint))
    changes = ""
    if choice == 1:
        changeJsonValue("Amount of videos to create: ", data, 'amountOfVideosToMake')
        changes = "updated video's to create successfully"
    elif choice == 2:    
        changeJsonValue("Your Pexels API key: ", data, 'pexelsAPIKey')
        changes = f"updated your API key successfully to - {data['pexelsAPIKey']}"
    elif choice == 3:
    verifyData(data)
    installed = checkIfImageMagicksIsInstalled()
    if installed:
        videoloop = mainVideoLoop(data)
        if videoloop:
            print(f"Succesfully completed making {data['amountOfVideosToMake']} video(s)")
        else:
            print("An error occurred somewhere above ^ (copy -> sent to developer)")
    else:
        print("ImageMagicks is needed to run the program...")
    input("Press enter to return to the main screen")
elif choice == 4:
    checkIfImageMagicksIsInstalled()
    input("Press enter to return to the main screen")
elif choice == 5:
    print("Exiting...")
    quit()
else:
    print("Invalid option! Example input: 1")

**Comment by DuxSec** [comment]
Glad you fixed it, otherwise you should download the release (executable). Then you won't have the python version issue ;)
