### ISSUE TITLE
ReWrite the same file on multiple generation

### ISSUE THREAD

**Issue by OMGerEDU** [fabrree/videoGenerator#9]
All works smoothly, but when I generate over 1 video, or even one, it overwrites the last one, and not creating a new one, so in that case it will always save only last created, no matter how many are been created.

Great work tho.

**Comment by OMGerEDU** [comment]
Actually, the problem is different,
Altho I changed the number of videos to be generated, it still thinks it wants a single video (And as above, overwrite the old one)

**Comment by DuxSec** [comment]
Hi, aware of the issue, will be fixed in next update :)

**Comment by DuxSec** [comment]
fixed
